---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: jenkins
  labels:
    name: gitlab
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 30022
  type: NodePort
  selector:
    name: gitlab
