kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-path
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---                                        
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  labels:
    name: gitlab
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /data/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node01
