apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitlab-pg-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pg-pv
  labels:
    name: postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: gitlab-pg-storage
  local:
    path: /data/gitlabpg
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: jenkins
spec:
  storageClassName: gitlab-pg-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
